### ISSUE TITLE
Creates invalid VTT files

### ISSUE THREAD

**Issue by needlestack** [woollybogger/srt-to-vtt-cl#1]
The timestamp format is supposed to use decimal points instead of commas. This program does not make that change.

**Comment by woollybogger** [comment]
@needlestack turns out you were right. The problem was that files with "\r\n" line endings weren't being handled correctly on OS X. This has been fixed in the [latest version](https://github.com/woollybogger/srt-to-vtt-cl/tree/master/bin/Mac-OSX).

**Comment by needlestack** [comment]
Great, thanks :)

**Comment by hoemaco** [comment]
I've encountered same problem (in 2021!).
Using the command line version for Windows 7 64b.
I made the srt file myself in NotePad2, using ANSI (ASCII) encoding. 
Only the WEBVTT header was placed in the file, the commas were unchanged.

**Comment by nwoltman** [comment]
@hoemaco Sounds like the cause for your issue might be slightly different since you're on Windows (and the original issue was on OS X). Please open a new issue using this template so I can better understand what's going wrong: https://github.com/nwoltman/srt-to-vtt-cl/issues/new?assignees=&labels=&template=conversion-bug-report.md&title=
