### ISSUE TITLE
UTF-8 ó -> &#243;

### ISSUE THREAD

**Issue by maczor** [woollybogger/srt-to-vtt-cl#2]
The "ó" is changed to &#243; during the SRT - VTT convertion

**Comment by woollybogger** [comment]
Hmm, I made it do this on purpose because I thought it prevented problems with how browsers render certain UTF-8 characters. I now realize that that was just a workaround for a bug in my implementation of [woollybogger/srt-to-vtt-converter](https://github.com/woollybogger/srt-to-vtt-converter) (a bug that I have since fixed in this project).

I should be able to fix this pretty quickly.
